# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pet_pet_id_body import PetPetIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestPetPetIdBody(unittest.TestCase):
    """PetPetIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPetPetIdBody(self):
        """Test PetPetIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pet_pet_id_body.PetPetIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
